#Available languages: en_US and pt_BR
language: en_US

allowed-cmds:
  - '/chain '
  - '/g '
  - '/. '

join-message-delay: 5

collect-points:
  delay: 300
  items:
    - DIAMOND_BLOCK;1
    - IRON_BLOCK;1

locations:

