main: br.com.craftlife.chain.ChainPlugin
name: ${project.name}
version: ${project.version}
description: ${project.description}
authors: [Brun0XP, WilliamEstrela]
website: www.craftlife.com.br

commands:
  chain:
    description: Main command